run:
  timeout: 5m

linters:
  enable:
    - errname
    - exhaustive
    - gci
    - goconst
    - godot
    - gofmt
    - makezero
    - perfsprint
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    ignore-tests: true
    min-len: 2
    min-occurrences: 2
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  perfsprint:
    strconcat: false
