run:
  timeout: 2m

linters:
  enable:
    - errname
    - exhaustive
    - exportloopref
    - goconst
    - godot
    - goimports
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    min-len: 2
    min-occurrences: 2
