run:
  timeout: 5m

linters:
  enable:
    - errname
    - exhaustive
    - exportloopref
    - gci
    - goconst
    - godot
    - gofmt
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
